configured_endpoints: 46
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/linkt-ai/linkt-f5fa3a92f5d301dbaac7f1170b03abae0aba88cdb0421aeed346fa8b03c1321a.yml
openapi_spec_hash: ac7b5aed12b1bca02394e0167d46072b
config_hash: 6c79fff24b4c328095aedeef70cfd015
