configured_endpoints: 41
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/linkt-ai%2Flinkt-eaca353fc984dbc91fa1ef1a1911ef1956ef57a91cd92cc9f0749b6d6b7f142b.yml
openapi_spec_hash: b23fbf05e47da72b5ca0c666ea1707ad
config_hash: 9b3ea4d174adac6f84af75eddf15a6ef
